
import { useState, useEffect } from 'react';
import { Plus, Trash2, Edit3, Search, X, BookOpen, CheckCircle, RotateCcw, Brain } from 'lucide-react';
const ACCENT='#8b5cf6'; const SK='pqc_v1'; const SS='pqc_s1'; const SO='pqc_o1';
type Page='dashboard'|'decks'|'study'|'quiz'|'progress'|'settings'|'help';
interface Card{id:string;front:string;back:string;difficulty:'easy'|'medium'|'hard';lastReviewed?:string;correct:number;attempts:number;}
interface Deck{id:string;name:string;subject:string;cards:Card[];description:string;isSample?:boolean;}
function ld<T>(k:string,fb:T):T{try{const v=localStorage.getItem(k);return v?JSON.parse(v):fb;}catch{return fb;}}
function sv<T>(k:string,v:T){localStorage.setItem(k,JSON.stringify(v));}
function uid(){return Math.random().toString(36).slice(2,10);}
const SAMPLE_DECKS:Deck[]=[
  {id:'d1',name:'JavaScript Fundamentals',subject:'Programming',description:'Core JS concepts for web development',isSample:true,cards:[
    {id:'c1',front:'What is a closure in JavaScript?',back:'A closure is a function that has access to its outer scope even after the outer function has returned. It captures variables from the enclosing scope.',difficulty:'medium',correct:0,attempts:0},
    {id:'c2',front:'What is the difference between let, const, and var?',back:'var: function-scoped, hoisted. let: block-scoped, not hoisted. const: block-scoped, cannot be reassigned (but object properties can be mutated).',difficulty:'easy',correct:0,attempts:0},
    {id:'c3',front:'What is event bubbling?',back:'Event bubbling is when an event triggered on a child element propagates up through all its ancestor elements in the DOM.',difficulty:'medium',correct:0,attempts:0},
    {id:'c4',front:'What is a Promise?',back:'A Promise is an object representing the eventual completion or failure of an asynchronous operation. States: pending, fulfilled, or rejected.',difficulty:'hard',correct:0,attempts:0},
    {id:'c5',front:'What is the difference between == and ===?',back:'== does type coercion before comparison (loose equality). === checks both value AND type without coercion (strict equality). Always prefer ===.',difficulty:'easy',correct:0,attempts:0},
  ]},
  {id:'d2',name:'Spanish A2 Vocabulary',subject:'Language',description:'Essential Spanish words for intermediate learners',isSample:true,cards:[
    {id:'c6',front:'¿Cuánto cuesta? (Spanish → English)',back:'How much does it cost?',difficulty:'easy',correct:0,attempts:0},
    {id:'c7',front:'Tengo hambre',back:'I am hungry',difficulty:'easy',correct:0,attempts:0},
    {id:'c8',front:'¿A qué hora...?',back:'At what time...?',difficulty:'easy',correct:0,attempts:0},
    {id:'c9',front:'Me gustaría reservar una mesa para dos',back:'I would like to reserve a table for two',difficulty:'medium',correct:0,attempts:0},
    {id:'c10',front:'¿Podría ayudarme, por favor?',back:'Could you help me, please?',difficulty:'medium',correct:0,attempts:0},
  ]},
];
export default function App(){
  const [decks,setDecks]=useState<Deck[]>(()=>ld(SK,[]));
  const [onboarded,setOnboarded]=useState(()=>ld(SO,false));
  const [page,setPage]=useState<Page>('dashboard');
  const [activeDeck,setActiveDeck]=useState<Deck|null>(null);
  const [modal,setModal]=useState<'deck'|'card'|null>(null);
  const [studyIdx,setStudyIdx]=useState(0);
  const [showAnswer,setShowAnswer]=useState(false);
  const [quizMode,setQuizMode]=useState(false);
  const [quizAnswer,setQuizAnswer]=useState('');
  const [quizScore,setQuizScore]=useState({correct:0,total:0,done:false});
  const [theme,setTheme]=useState(()=>ld(SS,{theme:'system'}).theme);
  const [deckForm,setDeckForm]=useState({name:'',subject:'',description:''});
  const [cardForm,setCardForm]=useState({front:'',back:'',difficulty:'medium' as Card['difficulty']});
  useEffect(()=>{sv(SK,decks);},[decks]);
  useEffect(()=>{const el=document.documentElement;if(theme==='dark')el.classList.add('dark');else if(theme==='light')el.classList.remove('dark');else{window.matchMedia('(prefers-color-scheme: dark)').matches?el.classList.add('dark'):el.classList.remove('dark');}sv(SS,{theme});},[theme]);
  const start=(s:boolean)=>{if(s)setDecks(SAMPLE_DECKS);setOnboarded(true);sv(SO,true);};
  const saveDeck=()=>{const d:Deck={id:uid(),...deckForm,cards:[]};setDecks(prev=>[d,...prev]);setModal(null);};
  const saveCard=()=>{if(!activeDeck)return;const c:Card={id:uid(),...cardForm,correct:0,attempts:0};setDecks(prev=>prev.map(d=>d.id===activeDeck.id?{...d,cards:[...d.cards,c]}:d));setActiveDeck(prev=>prev?{...prev,cards:[...prev.cards,c]}:null);setModal(null);setCardForm({front:'',back:'',difficulty:'medium'});};
  const studyCard=activeDeck?.cards[studyIdx];
  const startStudy=(deck:Deck)=>{setActiveDeck(deck);setStudyIdx(0);setShowAnswer(false);setQuizMode(false);setPage('study');};
  const startQuiz=(deck:Deck)=>{setActiveDeck(deck);setStudyIdx(0);setQuizMode(true);setQuizAnswer('');setQuizScore({correct:0,total:0,done:false});setPage('quiz');};
  const markCard=(correct:boolean)=>{if(!activeDeck||!studyCard)return;const updated={...studyCard,attempts:studyCard.attempts+1,correct:studyCard.correct+(correct?1:0),lastReviewed:new Date().toISOString()};setDecks(prev=>prev.map(d=>d.id===activeDeck.id?{...d,cards:d.cards.map(c=>c.id===updated.id?updated:c)}:d));setActiveDeck(prev=>prev?{...prev,cards:prev.cards.map(c=>c.id===updated.id?updated:c)}:null);if(studyIdx<activeDeck.cards.length-1){setStudyIdx(i=>i+1);setShowAnswer(false);}else{setPage('decks');}};
  const checkQuiz=()=>{if(!activeDeck||!studyCard)return;const correct=quizAnswer.trim().toLowerCase()===studyCard.back.toLowerCase().slice(0,50).toLowerCase()||studyCard.back.toLowerCase().includes(quizAnswer.toLowerCase());setQuizScore(s=>({...s,correct:s.correct+(correct?1:0),total:s.total+1}));if(studyIdx<activeDeck.cards.length-1){setStudyIdx(i=>i+1);setQuizAnswer('');}else{setQuizScore(s=>({...s,done:true}));}};
  const totalCards=decks.reduce((s,d)=>s+d.cards.length,0);
  const studiedCards=decks.reduce((s,d)=>s+d.cards.filter(c=>c.attempts>0).length,0);
  const hasSample=decks.some(d=>d.isSample);
  if(!onboarded)return(<div className="min-h-screen flex items-center justify-center p-6" style={{background:`linear-gradient(135deg,${ACCENT},#6d28d9)`}}><div className="max-w-xl w-full text-center"><div className="text-6xl mb-4">🧠</div><h1 className="text-3xl font-bold text-white mb-2">PDF to Quiz Coach</h1><p className="text-purple-100 mb-8">Turn your study notes into flashcards and quizzes.</p><div className="grid grid-cols-2 gap-4 text-left"><button onClick={()=>start(false)} className="bg-white/10 hover:bg-white/20 border-2 border-white/30 rounded-2xl p-6 text-white"><div className="text-2xl mb-2">📋</div><div className="font-semibold">Start Empty</div><div className="text-purple-200 text-sm mt-1">Create your own flashcard decks</div></button><button onClick={()=>start(true)} className="bg-white rounded-2xl p-6 text-left hover:bg-purple-50"><div className="text-2xl mb-2">✨</div><div className="font-semibold text-purple-700">Explore Sample Workspace</div><div className="text-purple-600 text-sm mt-1">JS + Spanish decks preloaded</div><div className="text-purple-400 text-xs mt-2">Sample data · Remove anytime</div></button></div><p className="text-purple-300 text-xs mt-4">One-time paid app · No subscription · Fully unlocked</p></div></div>);
  const Nav=({id,label}:{id:Page;label:string})=>(<button onClick={()=>setPage(id)} className={`px-3 py-2 rounded-xl text-sm font-medium transition-colors ${page===id?'text-white':'text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800'}`} style={page===id?{backgroundColor:ACCENT}:{}}>{label}</button>);
  return(<div className="min-h-screen bg-gray-50 dark:bg-gray-950 text-gray-900 dark:text-white">
    <header className="bg-white dark:bg-gray-900 border-b border-gray-100 dark:border-gray-800 px-6 py-3 flex items-center justify-between">
      <div className="flex items-center gap-3"><div className="w-8 h-8 rounded-lg flex items-center justify-center text-white text-sm" style={{backgroundColor:ACCENT}}>🧠</div><nav className="flex gap-1"><Nav id="dashboard" label="Dashboard"/><Nav id="decks" label="Decks"/><Nav id="settings" label="Settings"/><Nav id="help" label="Help"/></nav></div>
      <div className="flex items-center gap-2"><button onClick={()=>setTheme((t:string)=>t==='dark'?'light':'dark')} className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-500">{theme==='dark'?'☀️':'🌙'}</button>{page==='decks'&&<button onClick={()=>{setDeckForm({name:'',subject:'',description:''});setModal('deck');}} className="flex items-center gap-2 px-4 py-2 rounded-xl text-white text-sm font-medium" style={{backgroundColor:ACCENT}}><Plus size={15}/>New Deck</button>}</div>
    </header>
    <main className="max-w-5xl mx-auto p-6 space-y-6">
      {page==='dashboard'&&(<><div className="grid grid-cols-3 gap-4"><div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-100 dark:border-gray-800 p-5"><div className="text-2xl mb-2">📚</div><div className="text-2xl font-bold">{decks.length}</div><div className="text-sm text-gray-500">Study Decks</div></div><div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-100 dark:border-gray-800 p-5"><div className="text-2xl mb-2">🃏</div><div className="text-2xl font-bold">{totalCards}</div><div className="text-sm text-gray-500">Total Cards</div></div><div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-100 dark:border-gray-800 p-5"><div className="text-2xl mb-2">✅</div><div className="text-2xl font-bold">{studiedCards}</div><div className="text-sm text-gray-500">Cards Studied</div></div></div>
      {hasSample&&<div className="flex items-center justify-between bg-amber-50 dark:bg-amber-900/20 border border-amber-200 rounded-xl px-4 py-3"><span className="text-amber-700 dark:text-amber-400 text-sm">✦ Sample workspace loaded</span><button onClick={()=>setDecks(prev=>prev.filter(d=>!d.isSample))} className="text-xs text-amber-600 underline">Remove</button></div>}
      <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-100 dark:border-gray-800 p-5"><h2 className="font-semibold mb-4">Your Decks</h2>{decks.length===0?<div className="text-center py-8 text-gray-400"><Brain size={32} className="mx-auto mb-2"/><p>No decks yet — create your first deck</p><button onClick={()=>{setDeckForm({name:'',subject:'',description:''});setModal('deck');setPage('decks');}} className="mt-3 px-4 py-2 rounded-xl text-white text-sm" style={{backgroundColor:ACCENT}}>Create Deck</button></div>:decks.map(d=>(<div key={d.id} className="flex items-center gap-4 py-3 border-b border-gray-50 dark:border-gray-800 last:border-0"><div className="flex-1"><div className="flex items-center gap-2"><span className="font-medium text-sm">{d.name}</span>{d.isSample&&<span className="text-xs bg-amber-100 text-amber-700 px-2 py-0.5 rounded">✦ Sample</span>}</div><p className="text-xs text-gray-400">{d.subject} · {d.cards.length} cards</p></div><div className="flex gap-2"><button onClick={()=>startStudy(d)} className="px-3 py-1.5 rounded-xl text-white text-xs font-medium" style={{backgroundColor:ACCENT}}>Study</button><button onClick={()=>startQuiz(d)} className="px-3 py-1.5 rounded-xl border border-gray-200 dark:border-gray-700 text-xs">Quiz</button></div></div>))}</div></>)}
      {page==='decks'&&<div className="space-y-4">{decks.length===0&&<div className="text-center py-16"><div className="text-5xl mb-4">📚</div><p className="font-semibold text-lg mb-5">No decks yet</p><button onClick={()=>{setDeckForm({name:'',subject:'',description:''});setModal('deck');}} className="px-5 py-2.5 rounded-xl text-white font-medium" style={{backgroundColor:ACCENT}}>Create First Deck</button></div>}{decks.map(d=><div key={d.id} className="bg-white dark:bg-gray-900 rounded-xl border border-gray-100 dark:border-gray-800 p-5"><div className="flex items-start justify-between mb-3"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{d.name}</h3>{d.isSample&&<span className="text-xs bg-amber-100 text-amber-700 px-2 py-0.5 rounded">✦ Sample</span>}</div><p className="text-xs text-gray-400 mt-0.5">{d.subject} · {d.cards.length} cards</p></div><div className="flex gap-1"><button onClick={()=>{setActiveDeck(d);setCardForm({front:'',back:'',difficulty:'medium'});setModal('card');}} className="p-1.5 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg text-gray-400" title="Add card"><Plus size={15}/></button><button onClick={()=>setDecks(prev=>prev.filter(x=>x.id!==d.id))} className="p-1.5 hover:bg-red-50 rounded-lg text-gray-400 hover:text-red-500"><Trash2 size={15}/></button></div></div><p className="text-sm text-gray-500 mb-3">{d.description}</p><div className="flex gap-2"><button onClick={()=>startStudy(d)} className="px-4 py-2 rounded-xl text-white text-sm font-medium" style={{backgroundColor:ACCENT}}>Study</button><button onClick={()=>startQuiz(d)} className="px-4 py-2 rounded-xl border border-gray-200 dark:border-gray-700 text-sm">Take Quiz</button></div></div>)}</div>}
      {page==='study'&&activeDeck&&studyCard&&<div className="max-w-2xl mx-auto"><div className="text-sm text-gray-400 mb-3">{activeDeck.name} · Card {studyIdx+1} of {activeDeck.cards.length}</div><div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-8 text-center min-h-64 flex flex-col items-center justify-center"><p className="text-xs text-gray-400 mb-4 uppercase tracking-wide">Question</p><p className="text-xl font-medium leading-relaxed">{studyCard.front}</p>{showAnswer&&<><div className="w-full border-t border-gray-100 dark:border-gray-800 my-6"/><p className="text-xs text-gray-400 mb-2 uppercase tracking-wide">Answer</p><p className="text-lg text-gray-600 dark:text-gray-300 leading-relaxed">{studyCard.back}</p></>}</div>{!showAnswer?<button onClick={()=>setShowAnswer(true)} className="mt-4 w-full py-3 rounded-xl text-white font-medium" style={{backgroundColor:ACCENT}}>Show Answer</button>:<div className="flex gap-3 mt-4"><button onClick={()=>markCard(false)} className="flex-1 py-3 rounded-xl bg-red-50 text-red-600 font-medium">✗ Incorrect</button><button onClick={()=>markCard(true)} className="flex-1 py-3 rounded-xl bg-green-50 text-green-600 font-medium">✓ Correct</button></div>}<button onClick={()=>setPage('decks')} className="mt-3 w-full py-2 rounded-xl border border-gray-200 dark:border-gray-700 text-sm">Back to Decks</button></div>}
      {page==='quiz'&&activeDeck&&(<div className="max-w-2xl mx-auto">{quizScore.done?<div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-8 text-center"><div className="text-5xl mb-4">🎯</div><h2 className="text-2xl font-bold mb-2">Quiz Complete!</h2><p className="text-gray-500 mb-6">You scored {quizScore.correct} out of {quizScore.total}</p><div className="text-4xl font-bold mb-6" style={{color:ACCENT}}>{Math.round(quizScore.correct/quizScore.total*100)}%</div><button onClick={()=>setPage('decks')} className="px-6 py-3 rounded-xl text-white font-medium" style={{backgroundColor:ACCENT}}>Back to Decks</button></div>:studyCard&&(<><div className="text-sm text-gray-400 mb-3">Question {studyIdx+1} of {activeDeck.cards.length}</div><div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-8"><p className="font-medium text-lg mb-6">{studyCard.front}</p><input value={quizAnswer} onChange={e=>setQuizAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&checkQuiz()} placeholder="Type your answer…" className="w-full px-4 py-3 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 text-sm focus:outline-none focus:ring-2 mb-4"/><button onClick={checkQuiz} className="w-full py-3 rounded-xl text-white font-medium" style={{backgroundColor:ACCENT}}>Submit Answer</button></div></>)}</div>)}
      {page==='settings'&&<div className="max-w-lg space-y-4"><div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-100 dark:border-gray-800 p-5"><h3 className="font-semibold mb-3">Theme</h3><div className="flex gap-2">{['light','dark','system'].map(t=><button key={t} onClick={()=>setTheme(t)} className={`px-4 py-2 rounded-xl border text-sm capitalize ${theme===t?'text-white border-transparent':'border-gray-200 dark:border-gray-700'}`} style={theme===t?{backgroundColor:ACCENT}:{}}>{t}</button>)}</div></div><div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-100 dark:border-gray-800 p-5"><h3 className="font-semibold mb-2">About</h3><p className="text-sm text-gray-500">PDF to Quiz Coach · v1.0</p><p className="text-sm text-green-600 mt-1">✓ One-time paid app · No subscription</p></div></div>}
      {page==='help'&&<div className="max-w-2xl space-y-3">{[['How do I create a deck?','Click New Deck, enter a name and subject. Then add cards using the + button on each deck.'],['How does the quiz work?','The quiz shows you the front of each card and you type your answer. It checks if your answer matches the back of the card.'],['Can I import from a PDF?','Currently the app supports manual card entry. PDF import feature is coming in a future update.']].map(([q,a],i)=><div key={i} className="bg-white dark:bg-gray-900 rounded-xl border border-gray-100 dark:border-gray-800 p-5"><p className="font-medium text-sm mb-1">{q}</p><p className="text-sm text-gray-500">{a}</p></div>)}</div>}
    </main>
    {modal==='deck'&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={()=>setModal(null)}/><div className="relative w-full max-w-md bg-white dark:bg-gray-900 rounded-2xl shadow-2xl p-6"><div className="flex items-center justify-between mb-5"><h3 className="text-lg font-semibold">New Deck</h3><button onClick={()=>setModal(null)} className="p-1.5 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg text-gray-400"><X size={18}/></button></div><div className="space-y-4">{[{label:'Deck Name',key:'name'},{label:'Subject',key:'subject'},{label:'Description',key:'description'}].map(({label,key})=><div key={key}><label className="block text-sm font-medium text-gray-600 dark:text-gray-400 mb-1.5">{label}</label><input value={deckForm[key as keyof typeof deckForm]} onChange={e=>setDeckForm(f=>({...f,[key]:e.target.value}))} className="w-full px-3.5 py-2 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 text-sm focus:outline-none"/></div>)}<div className="flex gap-3"><button onClick={()=>setModal(null)} className="flex-1 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 text-sm">Cancel</button><button onClick={saveDeck} className="flex-1 py-2.5 rounded-xl text-white text-sm font-medium" style={{backgroundColor:ACCENT}}>Create Deck</button></div></div></div></div>}
    {modal==='card'&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={()=>setModal(null)}/><div className="relative w-full max-w-md bg-white dark:bg-gray-900 rounded-2xl shadow-2xl p-6"><div className="flex items-center justify-between mb-5"><h3 className="text-lg font-semibold">Add Flashcard</h3><button onClick={()=>setModal(null)} className="p-1.5 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg text-gray-400"><X size={18}/></button></div><div className="space-y-4"><div><label className="block text-sm font-medium text-gray-600 dark:text-gray-400 mb-1.5">Question (Front)</label><textarea value={cardForm.front} onChange={e=>setCardForm(f=>({...f,front:e.target.value}))} rows={3} className="w-full px-3.5 py-2 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 text-sm focus:outline-none resize-none"/></div><div><label className="block text-sm font-medium text-gray-600 dark:text-gray-400 mb-1.5">Answer (Back)</label><textarea value={cardForm.back} onChange={e=>setCardForm(f=>({...f,back:e.target.value}))} rows={3} className="w-full px-3.5 py-2 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 text-sm focus:outline-none resize-none"/></div><div><label className="block text-sm font-medium text-gray-600 dark:text-gray-400 mb-1.5">Difficulty</label><div className="flex gap-2">{(['easy','medium','hard'] as Card['difficulty'][]).map(d=><button key={d} onClick={()=>setCardForm(f=>({...f,difficulty:d}))} className={`flex-1 py-2 rounded-xl border text-sm capitalize ${cardForm.difficulty===d?'text-white border-transparent':'border-gray-200 dark:border-gray-700'}`} style={cardForm.difficulty===d?{backgroundColor:ACCENT}:{}}>{d}</button>)}</div></div><div className="flex gap-3"><button onClick={()=>setModal(null)} className="flex-1 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 text-sm">Cancel</button><button onClick={saveCard} className="flex-1 py-2.5 rounded-xl text-white text-sm font-medium" style={{backgroundColor:ACCENT}}>Add Card</button></div></div></div></div>}
  </div>);
}
